# -*- coding: utf-8 -*-
"""product_recommendation_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GS8FgZ5_3eT4l6jAY8Jb6z4knTqAStId

# **Welcome to the notebook**

Installing the needed modules
"""

!pip install openai==1.16.2 python-dotenv
!pip uninstall openai -y
!pip install --upgrade openai

"""Importing the needed modules and setup the OpenAI API"""

import pandas as pd
import numpy as np
import os
from dotenv import load_dotenv
from matplotlib import pyplot as plt
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import cosine_similarity
!pip install sentence-transformers
from sentence_transformers import SentenceTransformer

"""Import our dataset"""

data = pd.read_csv('products_dataset.csv')
data

"""List of last 8 products recently viewed by the user."""

searched_products_id = [
    'P1938',
    'P1970',
    'P1044',
    'P1838',
    'P1048',
    'P1017',
    'P1310',
    'P1444',
]

"""### Task 2 - Prepare the dataset

Let's label the data points that are recently veiwed.
"""

data["product_status"]="notviewed"
data.loc[data.product_id.isin(searched_products_id), "product_status"] = "recentlyviewed"
data[data.product_status=="recentlyviewed"]

"""Now let's combine the product `title` and `description` and store it into a column called `combined`."""

data["combined"] = data["title"] + " " + data["description"]
data

"""### Task 3 - Text embedding and visualization

Creating the text embedding vectors
"""

model = SentenceTransformer("all-MiniLM-L6-v2")
data["text_embeddings"] = data["combined"].apply(
    lambda x: model.encode(x)
)
print(data["text_embeddings"])

"""> We know that each vector has 384 dimensions. In order to be able to visualize the vectors in a scatter plot, we need to use Principal Component Analysis (PCA) to reduce the dimension from 384 to 2."""

import numpy as np
embedding_matrix = np.vstack(data["text_embeddings"].values)

pca = PCA(n_components=2)
vector_2d = pca.fit_transform(embedding_matrix)
data['pca_one'] = vector_2d[:, 0]
data['pca_two'] = vector_2d[:, 1]

"""Now that we have the text embedding vectors in two dimensions, we can use them to create a 2D plot."""

data
px.scatter(data,x='pca_one',y='pca_two',color="product_status")

"""### Task 4 - Find similar products"""

data.head()

"""Get the data related to `recently_viewed` and `not_viewed` products"""

df_recentlyviewed = data[data.product_status=="recentlyviewed"]
df_notviewed = data[data.product_status=="notviewed"]
df_recentlyviewed

"""Convert the embedding vectors to Numpy arrays"""

vectors_recently_viewed = [
    np.array(vector)
    for vector in df_recentlyviewed.text_embeddings
]
vectors_not_recently_viewed = [
    np.array(vector)
    for vector in df_notviewed.text_embeddings
]
vectors_recently_viewed

"""Find the similarity between each viewed product and all the unviewed products."""

similarity_matrix = cosine_similarity(vectors_recently_viewed, vectors_not_recently_viewed)
top_ids = []
for row in similarity_matrix:
  top_id = np.argmax(row)
  top_ids.append(top_id)
most_similar_product_ids = list(df_notviewed.iloc[top_ids].product_id)
most_similar_product_ids

"""### Task 5 - Recommend products based on the searched products

Let's update the status of the top similar products to `recommended`.
"""

data.loc[data.product_id.isin(most_similar_product_ids), "product_status"] = "recommended"
data[data.product_status=="recommended"]

"""Let's visualize the recommended products."""

px.scatter(data,x='pca_one',y='pca_two',color="product_status",hover_data="title")